### ISSUE TITLE
Переезд на поддомен

### ISSUE THREAD

**Issue by vlfz** [NellyD3v/pynepcord#1]
Отныне NeppedAPI работает на поддомене. Требуется переделать работу SDK для дальнейшей работы с API.
# Что требуется сделать?
Ранее чтобы обратиться к API, нужно было делать запрос на `neppedcord.top/api`. Теперь нужно делать запрос на `api.neppedcord.top` (без `/api`).

**Comment by NellyD3v** [comment]
The library has been updated. You can find the new version (1.0.1) on PyPI, or install it from source. Thanks.
